# Generated by Django 4.1 on 2023-11-11 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0003_ratingss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratingss',
            new_name='Ratings',
        ),
    ]
