# Generated by Django 4.1 on 2023-11-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_rename_ratingss_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name': 'Рейтинги', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='user',
            new_name='username',
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_user'),
        ),
    ]
