# Generated by Django 4.1 on 2023-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_ratings_options_rename_user_ratings_username_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ratings',
            name='unique_user',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='username',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
    ]
