# Generated by Django 4.1 on 2023-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_remove_ratings_unique_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ratings',
            name='unique_user',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='user',
            new_name='username',
        ),
        migrations.AddConstraint(
            model_name='ratings',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_user'),
        ),
    ]
